# Generated by Django 2.1.5 on 2019-09-17 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Infographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='infographics/', verbose_name='image')),
                ('description', martor.models.MartorField(blank=True, null=True, verbose_name='description')),
                ('embed_code', models.TextField(verbose_name='embed code')),
                ('lang', models.CharField(choices=[('tr', 'Turkish'), ('en', 'English')], max_length=5, verbose_name='language')),
                ('publish', models.BooleanField(default=False, verbose_name='publish')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
