# Generated by Django 2.1.5 on 2019-03-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('id',), 'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.RemoveField(
            model_name='section',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='article',
            name='lang',
            field=models.CharField(choices=[('tr', 'Turkish')], default='tr', max_length=5, verbose_name='language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='section',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
    ]
