# Generated by Django 2.1.5 on 2019-03-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='about_page',
            field=models.BooleanField(default=False, verbose_name='about page'),
        ),
    ]
