# Generated by Django 2.1.5 on 2019-04-18 12:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190330_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=tinymce.models.HTMLField(verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='section',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='text'),
        ),
    ]
