# Generated by Django 2.1.5 on 2019-04-25 20:52

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190418_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=martor.models.MartorField(verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='section',
            name='text',
            field=martor.models.MartorField(blank=True, null=True, verbose_name='text'),
        ),
    ]
