# Generated by Django 2.1.5 on 2019-06-14 08:37

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20190425_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=martor.models.MartorField(blank=True, null=True, verbose_name='summary'),
        ),
    ]
