# Generated by Django 2.1.5 on 2020-07-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200702_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('a', 'analysis'), ('r', 'report')], default='a', max_length=1),
        ),
    ]
