# Generated by Django 2.1.5 on 2019-02-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'institution', 'verbose_name_plural': 'institutions'},
        ),
        migrations.AlterModelOptions(
            name='journalist',
            options={'verbose_name': 'journalist', 'verbose_name_plural': 'journalists'},
        ),
        migrations.AlterModelOptions(
            name='journalistinstitution',
            options={'verbose_name': 'journalist institution', 'verbose_name_plural': 'journalist institutions'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'status', 'verbose_name_plural': 'status'},
        ),
        migrations.AlterModelOptions(
            name='workposition',
            options={'verbose_name': 'work position', 'verbose_name_plural': 'work positions'},
        ),
        migrations.AddField(
            model_name='journalist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='journalist',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], max_length=2, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='journalist',
            name='has_press_card',
            field=models.NullBooleanField(default=None, verbose_name='has press card'),
        ),
        migrations.AlterField(
            model_name='journalist',
            name='institutions',
            field=models.ManyToManyField(blank=True, through='journalists.JournalistInstitution', to='journalists.Institution', verbose_name='institutions'),
        ),
        migrations.AlterField(
            model_name='journalist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
