# Generated by Django 2.1.5 on 2019-02-06 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo')),
                ('gender', models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], max_length=2, null=True, verbose_name='gender')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='biography')),
            ],
            options={
                'verbose_name': 'journalist',
                'verbose_name_plural': 'journalists',
            },
        ),
        migrations.CreateModel(
            name='Attorney',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.Person')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'defence'), (2, 'prosecution')], verbose_name='type')),
            ],
            options={
                'verbose_name': 'attorney',
                'verbose_name_plural': 'attorneys',
            },
            bases=('people.person',),
        ),
        migrations.CreateModel(
            name='Journalist',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.Person')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'convict'), (2, 'detained'), (3, 'fugitive')], verbose_name='status')),
                ('status_change_date', models.DateField(blank=True, null=True, verbose_name='status change date')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('people.person',),
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.Person')),
            ],
            options={
                'verbose_name': 'judge',
                'verbose_name_plural': 'judges',
            },
            bases=('people.person',),
        ),
        migrations.CreateModel(
            name='Prosecutor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.Person')),
            ],
            options={
                'verbose_name': 'prosecutor',
                'verbose_name_plural': 'prosecutors',
            },
            bases=('people.person',),
        ),
        migrations.AddField(
            model_name='person',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_people.person_set+', to='contenttypes.ContentType'),
        ),
    ]
