# Generated by Django 2.1.5 on 2019-02-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalist',
            options={'verbose_name': 'journalist', 'verbose_name_plural': 'journalists'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
        migrations.AlterField(
            model_name='journalist',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'convict'), (2, 'detained'), (3, 'fugitive')], null=True, verbose_name='status'),
        ),
    ]
