# Generated by Django 2.1.5 on 2019-02-07 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20190207_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plaintiff',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.Person')),
            ],
            options={
                'verbose_name': 'plaintiff',
                'verbose_name_plural': 'plaintiffs',
            },
            bases=('people.person',),
        ),
    ]
