# Generated by Django 2.1.5 on 2019-02-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_plaintiff'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
