# Generated by Django 2.1.5 on 2019-02-20 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_person_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalistStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'free'), (1, 'convict'), (2, 'detained'), (3, 'fugitive')], null=True, verbose_name='status')),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
            ],
        ),
        migrations.RemoveField(
            model_name='journalist',
            name='status',
        ),
        migrations.RemoveField(
            model_name='journalist',
            name='status_change_date',
        ),
        migrations.AddField(
            model_name='journaliststatus',
            name='journalist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Journalist', verbose_name='journalist'),
        ),
    ]
