# Generated by Django 2.1.5 on 2019-02-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20190220_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorney',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'defence'), (2, 'prosecution')], default=1, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='journaliststatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'detained'), (2, 'imprisoned'), (3, 'convicted'), (4, 'released'), (5, 'fugitive')], default=0, verbose_name='status'),
            preserve_default=False,
        ),
    ]
