# Generated by Django 2.1.5 on 2019-02-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20190221_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journaliststatus',
            options={'verbose_name': 'journalist status', 'verbose_name_plural': 'journalist status'},
        ),
    ]
