# Generated by Django 2.1.5 on 2019-02-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20190223_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journaliststatus',
            name='date',
        ),
        migrations.AddField(
            model_name='journalist',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
        migrations.AddField(
            model_name='journaliststatus',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='journaliststatus',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start date'),
        ),
    ]
