# Generated by Django 2.1.5 on 2019-03-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20190223_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('name',), 'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
    ]
