# Generated by Django 2.1.5 on 2019-03-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20190304_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaliststatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'detained'), (2, 'imprisoned'), (3, 'convicted'), (4, 'fugitive')], verbose_name='status'),
        ),
    ]
