# Generated by Django 2.1.5 on 2019-03-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20190304_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='person',
            name='slug',
        ),
        migrations.AddField(
            model_name='journalist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='journalist',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journaliststatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'not detained'), (2, 'detained'), (3, 'imprisoned'), (4, 'convicted'), (5, 'fugitive')], verbose_name='status'),
        ),
    ]
