# Generated by Django 2.1.5 on 2019-03-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20190308_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalistnote',
            options={'verbose_name': 'journalist note', 'verbose_name_plural': 'journalist notes'},
        ),
    ]
