# Generated by Django 2.1.5 on 2019-03-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_auto_20190308_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaliststatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'not detained'), (2, 'detained'), (3, 'imprisoned'), (4, 'convicted'), (5, 'fugitive'), (6, 'postponed'), (7, 'judgement receded')], verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
    ]
