# Generated by Django 2.1.5 on 2019-03-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_auto_20190308_1149'),
    ]

    operations = [
    ]
