# Generated by Django 2.1.5 on 2019-03-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_auto_20190309_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalist',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
