# Generated by Django 2.1.5 on 2019-03-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20190309_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaliststatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'not detained'), (2, 'detained'), (3, 'imprisoned'), (4, 'convicted'), (5, 'fugitive'), (6, 'postponed'), (7, 'judgement receded')], verbose_name='status'),
        ),
    ]
