# Generated by Django 2.1.5 on 2019-03-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_auto_20190309_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalist',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
