# Generated by Django 2.1.5 on 2019-03-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_auto_20190310_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='journalists/', verbose_name='photo'),
        ),
    ]
