# Generated by Django 2.1.5 on 2019-03-20 13:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0019_auto_20190315_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 3, 20, 13, 3, 11, 850901, tzinfo=utc), verbose_name='added time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified time'),
        ),
        migrations.AddField(
            model_name='person',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='reporter'),
        ),
    ]
