# Generated by Django 2.1.5 on 2019-03-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0020_auto_20190320_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalistnote',
            options={'ordering': ('time',), 'verbose_name': 'journalist note', 'verbose_name_plural': 'journalist notes'},
        ),
    ]
