# Generated by Django 2.1.5 on 2019-03-23 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0004_auto_20190309_1633'),
        ('people', '0021_auto_20190322_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attorney',
            options={'ordering': ('name',), 'verbose_name': 'attorney', 'verbose_name_plural': 'attorneys'},
        ),
        migrations.AlterModelOptions(
            name='journalist',
            options={'ordering': ('name',), 'verbose_name': 'journalist', 'verbose_name_plural': 'journalists'},
        ),
        migrations.AlterModelOptions(
            name='journaliststatus',
            options={'ordering': ('-start_date',), 'verbose_name': 'journalist status', 'verbose_name_plural': 'journalist status'},
        ),
        migrations.AlterModelOptions(
            name='judge',
            options={'ordering': ('name',), 'verbose_name': 'judge', 'verbose_name_plural': 'judges'},
        ),
        migrations.AlterModelOptions(
            name='plaintiff',
            options={'ordering': ('name',), 'verbose_name': 'plaintiff', 'verbose_name_plural': 'plaintiffs'},
        ),
        migrations.AlterModelOptions(
            name='prosecutor',
            options={'ordering': ('name',), 'verbose_name': 'prosecutor', 'verbose_name_plural': 'prosecutors'},
        ),
        migrations.AddField(
            model_name='journaliststatus',
            name='prison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jurisdiction.Prison', verbose_name='journalist'),
        ),
        migrations.AlterField(
            model_name='journaliststatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Not detained'), (2, 'Detained'), (3, 'Imprisoned'), (4, 'Convicted'), (5, 'Fugitive'), (6, 'Postponed'), (7, 'Judgement receded')], verbose_name='status'),
        ),
    ]
