# Generated by Django 2.1.5 on 2019-03-23 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_auto_20190323_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalistDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/', verbose_name='file')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('journalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Journalist', verbose_name='journalist')),
            ],
            options={
                'verbose_name': 'journalist document',
                'verbose_name_plural': 'journalist documents',
            },
        ),
        migrations.CreateModel(
            name='JournalistDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='type')),
            ],
            options={
                'verbose_name': 'journalist document type',
                'verbose_name_plural': 'journalist document types',
            },
        ),
        migrations.AddField(
            model_name='journalistdocument',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.JournalistDocumentType', verbose_name='type'),
        ),
    ]
