# Generated by Django 2.1.5 on 2019-03-23 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0024_auto_20190323_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalistdocument',
            name='journalist',
        ),
        migrations.RemoveField(
            model_name='journalistdocument',
            name='type',
        ),
        migrations.DeleteModel(
            name='JournalistDocument',
        ),
        migrations.DeleteModel(
            name='JournalistDocumentType',
        ),
    ]
