# Generated by Django 2.1.5 on 2019-03-30 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0025_auto_20190323_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complainant',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.Person')),
            ],
            options={
                'verbose_name': 'complainant',
                'verbose_name_plural': 'complainants',
                'ordering': ('name',),
            },
            bases=('people.person',),
        ),
    ]
