# Generated by Django 2.1.5 on 2019-04-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0026_complainant'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='short_bio',
            field=models.TextField(blank=True, null=True, verbose_name='short bio'),
        ),
    ]
