# Generated by Django 2.1.5 on 2019-04-18 12:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0027_person_short_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalist',
            options={'ordering': ('slug', 'name'), 'verbose_name': 'journalist', 'verbose_name_plural': 'journalists'},
        ),
        migrations.AlterField(
            model_name='journalistnote',
            name='note',
            field=tinymce.models.HTMLField(verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='biography'),
        ),
        migrations.AlterField(
            model_name='person',
            name='short_bio',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='short bio'),
        ),
    ]
