# Generated by Django 2.1.5 on 2019-04-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0029_auto_20190425_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='short_bio',
            field=models.TextField(blank=True, null=True, verbose_name='short bio'),
        ),
    ]
