# Generated by Django 2.1.5 on 2019-08-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0032_auto_20190725_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaliststatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Not detained'), (2, 'Detained'), (3, 'Imprisoned'), (4, 'Convicted'), (5, 'Fugitive'), (6, 'Postponed'), (7, 'Judgement receded'), (8, 'Prisoner on remand'), (9, 'Acquitted'), (10, 'Judicial fine'), (11, 'Execution completed')], verbose_name='status'),
        ),
    ]
