# Generated by Django 2.1.5 on 2019-02-06 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=20, verbose_name='number')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('defendant_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='defendant count')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified time')),
            ],
            options={
                'verbose_name': 'case',
                'verbose_name_plural': 'case',
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'case document',
                'verbose_name_plural': 'case documents',
            },
        ),
        migrations.CreateModel(
            name='CaseDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'case document type',
                'verbose_name_plural': 'case document types',
            },
        ),
        migrations.CreateModel(
            name='CaseJournalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'reporter'), (2, 'editor')], null=True, verbose_name='position')),
            ],
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='note')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
            },
        ),
        migrations.CreateModel(
            name='CaseScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=200, verbose_name='scope')),
            ],
            options={
                'verbose_name': 'case scope',
                'verbose_name_plural': 'case scope',
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'interlocutory'), (2, 'definitive')], null=True, verbose_name='decision type')),
                ('punishment_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'imprisonment'), (2, 'fine'), (3, 'probation')], null=True, verbose_name='decision type')),
                ('punishment_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='punishment amount')),
                ('date', models.DateField(verbose_name='date')),
            ],
            options={
                'verbose_name': 'decision',
                'verbose_name_plural': 'decisions',
            },
        ),
        migrations.CreateModel(
            name='Indictment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True, verbose_name='details')),
                ('requested_punishment_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'imprisonment'), (2, 'fine')], null=True, verbose_name='requested punishment type')),
                ('requested_punishment_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='requested punishment amount')),
                ('date', models.DateField(verbose_name='date')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case', verbose_name='case')),
            ],
            options={
                'verbose_name': 'indictment',
                'verbose_name_plural': 'indictments',
            },
        ),
        migrations.CreateModel(
            name='IndictmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=200, verbose_name='definition')),
            ],
            options={
                'verbose_name': 'indictment type',
                'verbose_name_plural': 'indictment types',
            },
        ),
        migrations.CreateModel(
            name='NoteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='type')),
            ],
            options={
                'verbose_name': 'note type',
                'verbose_name_plural': 'note types',
            },
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_no', models.PositiveIntegerField(verbose_name='session')),
                ('time', models.DateTimeField(verbose_name='time')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='summary')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='added time')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case', verbose_name='case')),
                ('observers', models.ManyToManyField(blank=True, to='institutions.Institution', verbose_name='institutional observers')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='reporter')),
            ],
            options={
                'verbose_name': 'trial',
                'verbose_name_plural': 'trials',
            },
        ),
        migrations.CreateModel(
            name='TrialDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Trial', verbose_name='trial')),
            ],
            options={
                'verbose_name': 'trial document',
                'verbose_name_plural': 'trial documents',
            },
        ),
        migrations.CreateModel(
            name='TrialDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'trial document type',
                'verbose_name_plural': 'trial document types',
            },
        ),
        migrations.CreateModel(
            name='TrialNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='note')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.NoteType', verbose_name='type')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
            },
        ),
        migrations.CreateModel(
            name='TrialViolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True, verbose_name='details')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Trial', verbose_name='trial')),
            ],
            options={
                'verbose_name': 'right violation',
                'verbose_name_plural': 'right violations',
            },
        ),
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='type')),
            ],
            options={
                'verbose_name': 'violation type',
                'verbose_name_plural': 'violation types',
            },
        ),
        migrations.AddField(
            model_name='trialviolation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.ViolationType', verbose_name='violation type'),
        ),
        migrations.AddField(
            model_name='trialdocument',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.TrialDocumentType', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='indictment',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.IndictmentType', verbose_name='indictment type'),
        ),
    ]
