# Generated by Django 2.1.5 on 2019-03-04 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0002_remove_institution_short_name'),
        ('jurisdiction', '0003_auto_20190207_2129'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0009_auto_20190304_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'TCK'), (2, 'TMK'), (3, 'Constitution')])),
                ('no', models.CharField(max_length=20)),
                ('punishment_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'fine'), (2, 'imprisonment')], null=True, verbose_name='punishment type')),
                ('punishment_amount_min', models.CharField(blank=True, max_length=100, null=True, verbose_name='minimum punishment due')),
                ('punishment_amount_max', models.CharField(blank=True, max_length=100, null=True, verbose_name='maximum punishment due')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=20, verbose_name='file number')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('filing_date', models.DateField(blank=True, null=True, verbose_name='case filing date')),
                ('opening_date', models.DateField(blank=True, null=True, verbose_name='case opening date')),
                ('defendant_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='defendant count')),
                ('coup_related', models.BooleanField(default=False, verbose_name='coup attempt related')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('board', models.ManyToManyField(blank=True, related_name='board_memberships', to='people.Judge', verbose_name='board of judges')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jurisdiction.Court', verbose_name='court')),
            ],
            options={
                'verbose_name': 'case',
                'verbose_name_plural': 'cases',
            },
        ),
        migrations.CreateModel(
            name='CaseAttorney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Attorney', verbose_name='attorney')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case', verbose_name='case')),
                ('journalists', models.ManyToManyField(blank=True, to='people.Journalist', verbose_name='journalists')),
            ],
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case', verbose_name='case')),
            ],
            options={
                'verbose_name': 'case document',
                'verbose_name_plural': 'case documents',
            },
        ),
        migrations.CreateModel(
            name='CaseDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='type')),
            ],
            options={
                'verbose_name': 'case document type',
                'verbose_name_plural': 'case document types',
            },
        ),
        migrations.CreateModel(
            name='CaseIndictment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True, verbose_name='details')),
                ('articles', models.ManyToManyField(to='cases.Article', verbose_name='articles')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case', verbose_name='case')),
            ],
            options={
                'verbose_name': 'indictment',
                'verbose_name_plural': 'indictments',
            },
        ),
        migrations.CreateModel(
            name='CaseJournalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'acquittal'), (1, 'fine'), (2, 'imprisonment')], null=True, verbose_name='decision type')),
                ('punishment_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='punishment amount')),
                ('articles', models.ManyToManyField(to='cases.Article', verbose_name='articles')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case', verbose_name='case')),
            ],
            options={
                'verbose_name': 'case - journalist relation',
                'verbose_name_plural': 'case - journalist relations',
            },
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='note')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case', verbose_name='case')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
            },
        ),
        migrations.CreateModel(
            name='CaseScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=200, verbose_name='scope')),
            ],
            options={
                'verbose_name': 'case scope',
                'verbose_name_plural': 'case scope',
            },
        ),
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'local'), (1, 'appeal'), (2, 'supreme'), (3, 'constitutional'), (4, 'ECHR')], default=1)),
                ('date', models.DateField(blank=True, null=True)),
                ('decision', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'approved'), (2, 'denied')], null=True)),
                ('details', models.TextField(blank=True, null=True, verbose_name='details')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case', verbose_name='case')),
            ],
            options={
                'verbose_name': 'case status',
                'verbose_name_plural': 'case status',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Indictment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='category')),
                ('definition', models.CharField(max_length=200, verbose_name='type')),
            ],
            options={
                'verbose_name': 'indictment type',
                'verbose_name_plural': 'indictment types',
            },
        ),
        migrations.CreateModel(
            name='NoteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='type')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
            ],
            options={
                'verbose_name': 'note type',
                'verbose_name_plural': 'note types',
            },
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_no', models.PositiveIntegerField(verbose_name='session')),
                ('time_announced', models.DateTimeField(verbose_name='announced time')),
                ('time_start', models.DateTimeField(blank=True, null=True, verbose_name='start time')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='summary')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='added time')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case', verbose_name='case')),
                ('observers', models.ManyToManyField(blank=True, to='institutions.Institution', verbose_name='institutional observers')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='reporter')),
            ],
            options={
                'verbose_name': 'trial',
                'verbose_name_plural': 'trials',
            },
        ),
        migrations.CreateModel(
            name='TrialDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Trial', verbose_name='trial')),
            ],
            options={
                'verbose_name': 'trial document',
                'verbose_name_plural': 'trial documents',
            },
        ),
        migrations.CreateModel(
            name='TrialDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='type')),
            ],
            options={
                'verbose_name': 'trial document type',
                'verbose_name_plural': 'trial document types',
            },
        ),
        migrations.CreateModel(
            name='TrialNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Trial', verbose_name='trial')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.NoteType', verbose_name='type')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
            },
        ),
        migrations.CreateModel(
            name='TrialViolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True, verbose_name='details')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Trial', verbose_name='trial')),
            ],
            options={
                'verbose_name': 'right violation',
                'verbose_name_plural': 'right violations',
            },
        ),
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='type')),
            ],
            options={
                'verbose_name': 'violation type',
                'verbose_name_plural': 'violation types',
            },
        ),
        migrations.CreateModel(
            name='WorkPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='work position')),
            ],
            options={
                'verbose_name': 'work position',
                'verbose_name_plural': 'work position',
            },
        ),
        migrations.AddField(
            model_name='trialviolation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.ViolationType', verbose_name='violation type'),
        ),
        migrations.AddField(
            model_name='trialdocument',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.TrialDocumentType', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='casenote',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.NoteType', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='casejournalist',
            name='indictment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.Indictment', verbose_name='indictment type'),
        ),
        migrations.AddField(
            model_name='casejournalist',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.Institution', verbose_name='institution'),
        ),
        migrations.AddField(
            model_name='casejournalist',
            name='journalist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Journalist', verbose_name='journalists'),
        ),
        migrations.AddField(
            model_name='casejournalist',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.WorkPosition', verbose_name='work position'),
        ),
        migrations.AddField(
            model_name='caseindictment',
            name='indictment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.Indictment', verbose_name='indictment type'),
        ),
        migrations.AddField(
            model_name='caseindictment',
            name='journalists',
            field=models.ManyToManyField(blank=True, to='people.Journalist', verbose_name='journalists'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.CaseDocumentType', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='case',
            name='defendant_attorneys',
            field=models.ManyToManyField(blank=True, through='cases.CaseAttorney', to='people.Attorney', verbose_name='defendant attorneys'),
        ),
        migrations.AddField(
            model_name='case',
            name='journalists',
            field=models.ManyToManyField(through='cases.CaseJournalist', to='people.Journalist'),
        ),
        migrations.AddField(
            model_name='case',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Judge', verbose_name='presiding judge'),
        ),
        migrations.AddField(
            model_name='case',
            name='plaintiff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Plaintiff', verbose_name='plaintiff'),
        ),
        migrations.AddField(
            model_name='case',
            name='prosecutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Prosecutor', verbose_name='prosecutor'),
        ),
        migrations.AddField(
            model_name='case',
            name='related_cases',
            field=models.ManyToManyField(blank=True, related_name='_case_related_cases_+', to='cases.Case', verbose_name='related cases'),
        ),
        migrations.AddField(
            model_name='case',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='reporter'),
        ),
        migrations.AddField(
            model_name='case',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.CaseScope', verbose_name='case scope'),
        ),
    ]
