# Generated by Django 2.1.5 on 2019-02-01 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journalists', '0001_initial'),
        ('jurisdiction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('start_date', models.DateField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jurisdiction.Court')),
                ('parent_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.Case')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punishment_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('is_final', models.BooleanField(default=False)),
                ('journalists', models.ManyToManyField(blank=True, to='journalists.Journalist')),
                ('punishment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jurisdiction.PunishmentType')),
            ],
        ),
        migrations.CreateModel(
            name='Indictment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_punishment_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='requested punishment amount')),
                ('date', models.DateField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
                ('journalists', models.ManyToManyField(blank=True, to='journalists.Journalist')),
                ('requested_punishment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jurisdiction.PunishmentType', verbose_name='requested punishment type')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jurisdiction.IndictmentType')),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_no', models.PositiveIntegerField()),
                ('journalist_count', models.PositiveIntegerField()),
                ('defendant_count', models.PositiveIntegerField()),
                ('time', models.DateTimeField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('attorneys', models.ManyToManyField(blank=True, to='jurisdiction.Attorney')),
                ('board', models.ManyToManyField(blank=True, related_name='board_memberships', to='jurisdiction.Judge')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jurisdiction.Judge')),
                ('observers', models.ManyToManyField(blank=True, to='journalists.Institution', verbose_name='Institutional observers')),
                ('prosecutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jurisdiction.Prosecutor')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jurisdiction.TrialType')),
            ],
        ),
        migrations.CreateModel(
            name='TrialDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Trial')),
            ],
        ),
        migrations.CreateModel(
            name='TrialDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrialViolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Trial')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jurisdiction.ViolationType')),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('for_against', models.NullBooleanField()),
            ],
            options={
                'verbose_name': 'witness',
                'verbose_name_plural': 'witnesses',
            },
        ),
        migrations.CreateModel(
            name='WitnessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='witness',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.WitnessType'),
        ),
        migrations.AddField(
            model_name='trialdocument',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.TrialDocumentType'),
        ),
        migrations.AddField(
            model_name='trial',
            name='witnesses',
            field=models.ManyToManyField(blank=True, to='cases.Witness'),
        ),
        migrations.AddField(
            model_name='decision',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Trial'),
        ),
        migrations.AddField(
            model_name='decision',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jurisdiction.DecisionType'),
        ),
    ]
