# Generated by Django 2.1.5 on 2019-03-04 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20190304_1321'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'acquittal'), (1, 'fine'), (2, 'imprisonment')], null=True, verbose_name='decision type')),
                ('punishment_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='punishment amount')),
            ],
            options={
                'verbose_name': 'case - decision relation',
                'verbose_name_plural': 'case - decision relations',
            },
        ),
        migrations.RemoveField(
            model_name='caseattorney',
            name='attorney',
        ),
        migrations.RemoveField(
            model_name='caseattorney',
            name='case',
        ),
        migrations.RemoveField(
            model_name='caseattorney',
            name='journalists',
        ),
        migrations.RemoveField(
            model_name='case',
            name='defendant_attorneys',
        ),
        migrations.RemoveField(
            model_name='caseindictment',
            name='journalists',
        ),
        migrations.RemoveField(
            model_name='casejournalist',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='casejournalist',
            name='decision_type',
        ),
        migrations.RemoveField(
            model_name='casejournalist',
            name='indictment',
        ),
        migrations.RemoveField(
            model_name='casejournalist',
            name='punishment_amount',
        ),
        migrations.AddField(
            model_name='caseindictment',
            name='journalist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='people.Journalist', verbose_name='journalist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casejournalist',
            name='attorneys',
            field=models.ManyToManyField(to='people.Attorney', verbose_name='attorney'),
        ),
        migrations.AlterField(
            model_name='caseindictment',
            name='articles',
            field=models.ManyToManyField(blank=True, to='cases.Article', verbose_name='articles'),
        ),
        migrations.DeleteModel(
            name='CaseAttorney',
        ),
        migrations.AddField(
            model_name='casedecision',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case', verbose_name='case'),
        ),
        migrations.AddField(
            model_name='casedecision',
            name='journalist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Journalist', verbose_name='journalists'),
        ),
    ]
