# Generated by Django 2.1.5 on 2019-02-07 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20190206_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'case', 'verbose_name_plural': 'cases'},
        ),
        migrations.AlterModelOptions(
            name='casejournalist',
            options={'verbose_name': 'case', 'verbose_name_plural': 'cases'},
        ),
        migrations.AddField(
            model_name='casenote',
            name='case',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cases.Case', verbose_name='case'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trialnote',
            name='trial',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cases.Trial', verbose_name='trial'),
            preserve_default=False,
        ),
    ]
