# Generated by Django 2.1.5 on 2019-03-05 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20190304_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casenote',
            options={'verbose_name': 'case note', 'verbose_name_plural': 'case notes'},
        ),
        migrations.AlterModelOptions(
            name='trialnote',
            options={'verbose_name': 'trial note', 'verbose_name_plural': 'trial notes'},
        ),
    ]
