# Generated by Django 2.1.5 on 2019-02-04 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20190204_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'case document',
                'verbose_name_plural': 'case documents',
            },
        ),
        migrations.CreateModel(
            name='CaseDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'case document type',
                'verbose_name_plural': 'case document types',
            },
        ),
        migrations.RemoveField(
            model_name='trial',
            name='defendant_count',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='journalist_count',
        ),
        migrations.AddField(
            model_name='case',
            name='defendant_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='defendant count'),
        ),
        migrations.AddField(
            model_name='case',
            name='journalist_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='journalist count'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case', verbose_name='case'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.CaseDocumentType', verbose_name='type'),
        ),
    ]
