# Generated by Django 2.1.5 on 2019-02-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20190207_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='next_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='next trial time'),
        ),
    ]
