# Generated by Django 2.1.5 on 2019-03-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20190305_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ('-modified',), 'verbose_name': 'case', 'verbose_name_plural': 'cases'},
        ),
        migrations.AlterModelOptions(
            name='trial',
            options={'ordering': ('-modified',), 'verbose_name': 'trial', 'verbose_name_plural': 'trials'},
        ),
        migrations.AddField(
            model_name='case',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
        migrations.AddField(
            model_name='trial',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
    ]
