# Generated by Django 2.1.5 on 2019-03-07 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('cases', '0004_auto_20190305_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialNoteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='type')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
            ],
            options={
                'verbose_name': 'trial note type',
                'verbose_name_plural': 'trial note types',
            },
        ),
        migrations.RenameModel(
            old_name='NoteType',
            new_name='CaseNoteType',
        ),
        migrations.AlterModelOptions(
            name='casenotetype',
            options={'verbose_name': 'case note type', 'verbose_name_plural': 'case note types'},
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(default='x', max_length=100, verbose_name='case name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='publish'),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='publish'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='publish'),
        ),
        migrations.AlterField(
            model_name='trialnote',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.TrialNoteType', verbose_name='type'),
        ),
    ]
