# Generated by Django 2.1.5 on 2019-02-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20190207_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='name',
        ),
    ]
