# Generated by Django 2.1.5 on 2019-03-09 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_auto_20190309_1633'),
        ('cases', '0006_remove_indictment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='board',
        ),
        migrations.RemoveField(
            model_name='case',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='caseindictment',
            name='indictment',
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='article'),
        ),
        migrations.AddField(
            model_name='article',
            name='indictment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='indictment'),
        ),
        migrations.AddField(
            model_name='casedecision',
            name='articles',
            field=models.ManyToManyField(blank=True, to='cases.Article', verbose_name='articles'),
        ),
        migrations.AddField(
            model_name='trial',
            name='board',
            field=models.ManyToManyField(blank=True, related_name='board_memberships', to='people.Judge', verbose_name='board of judges'),
        ),
        migrations.AddField(
            model_name='trial',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Judge', verbose_name='presiding judge'),
        ),
        migrations.AddField(
            model_name='trial',
            name='prosecutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Prosecutor', verbose_name='indictment prosecutor'),
        ),
        migrations.AddField(
            model_name='trial',
            name='time_next',
            field=models.DateTimeField(blank=True, null=True, verbose_name='next trial time'),
        ),
        migrations.RemoveField(
            model_name='case',
            name='plaintiff',
        ),
        migrations.AddField(
            model_name='case',
            name='plaintiff',
            field=models.ManyToManyField(blank=True, to='people.Plaintiff', verbose_name='plaintiff'),
        ),
        migrations.AlterField(
            model_name='case',
            name='prosecutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Prosecutor', verbose_name='indictment prosecutor'),
        ),
        migrations.DeleteModel(
            name='Indictment',
        ),
    ]
