# Generated by Django 2.1.5 on 2019-02-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_remove_case_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casejournalist',
            options={'verbose_name': 'case - journalist relation', 'verbose_name_plural': 'case - journalist relations'},
        ),
        migrations.RemoveField(
            model_name='casejournalist',
            name='punishment_type',
        ),
        migrations.AddField(
            model_name='casejournalist',
            name='decision_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'acquittal'), (2, 'fine'), (3, 'imprisonment')], null=True, verbose_name='punishment type'),
        ),
    ]
