# Generated by Django 2.1.5 on 2019-02-07 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20190207_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='work position')),
            ],
            options={
                'verbose_name': 'work position',
                'verbose_name_plural': 'work position',
            },
        ),
        migrations.AlterField(
            model_name='casejournalist',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.WorkPosition', verbose_name='work position'),
        ),
    ]
