# Generated by Django 2.1.5 on 2019-03-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20190309_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casedecision',
            old_name='punishment_amount',
            new_name='punishment_fine',
        ),
        migrations.AddField(
            model_name='casedecision',
            name='punishment_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='day'),
        ),
        migrations.AddField(
            model_name='casedecision',
            name='punishment_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='month'),
        ),
        migrations.AddField(
            model_name='casedecision',
            name='punishment_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year'),
        ),
    ]
