# Generated by Django 2.1.5 on 2019-03-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20190309_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedecision',
            name='punishment_fine',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='fine'),
        ),
    ]
