# Generated by Django 2.1.5 on 2019-02-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20190207_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='filing_date',
            field=models.DateField(blank=True, null=True, verbose_name='filing date'),
        ),
    ]
