# Generated by Django 2.1.5 on 2019-02-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_case_filing_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casedocumenttype',
            name='file',
        ),
    ]
