# Generated by Django 2.1.5 on 2019-02-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_remove_casedocumenttype_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casedocumenttype',
            name='description',
        ),
        migrations.AddField(
            model_name='casedocumenttype',
            name='type',
            field=models.CharField(default='-', max_length=50, verbose_name='type'),
            preserve_default=False,
        ),
    ]
