# Generated by Django 2.1.5 on 2019-03-15 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_case_journalist_defendant_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedocument',
            name='file',
            field=models.FileField(upload_to='documents/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='prosecutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Prosecutor', verbose_name='trial prosecutor'),
        ),
        migrations.AlterField(
            model_name='trialdocument',
            name='file',
            field=models.FileField(upload_to='documents/', verbose_name='file'),
        ),
    ]
