# Generated by Django 2.1.5 on 2019-03-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_auto_20190315_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedecision',
            name='decision_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'acquittal'), (1, 'fine'), (2, 'imprisonment'), (6, 'postponed'), (7, 'judgement receded')], null=True, verbose_name='decision type'),
        ),
    ]
