# Generated by Django 2.1.5 on 2019-02-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_auto_20190209_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indictmenttype',
            old_name='definition',
            new_name='type',
        ),
    ]
