# Generated by Django 2.1.5 on 2019-03-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_auto_20190316_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='scope',
        ),
        migrations.DeleteModel(
            name='CaseScope',
        ),
    ]
