# Generated by Django 2.1.5 on 2019-02-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_auto_20190209_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indictmenttype',
            name='type',
            field=models.CharField(max_length=200, verbose_name='type'),
        ),
    ]
