# Generated by Django 2.1.5 on 2019-02-20 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_auto_20190209_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'appeal'), (2, 'supreme'), (3, 'constitutional'), (4, 'ECHR')], default=1)),
                ('date', models.DateField(blank=True, null=True)),
                ('decision', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'approved'), (2, 'denied')], null=True)),
            ],
            options={
                'verbose_name': 'case status',
                'verbose_name_plural': 'case status',
                'ordering': ('date',),
            },
        ),
        migrations.RemoveField(
            model_name='case',
            name='parent_case',
        ),
        migrations.AddField(
            model_name='case',
            name='related_cases',
            field=models.ManyToManyField(blank=True, related_name='_case_related_cases_+', to='cases.Case', verbose_name='related cases'),
        ),
        migrations.AddField(
            model_name='casestatus',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case', verbose_name='case'),
        ),
    ]
