# Generated by Django 2.1.5 on 2019-02-20 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_auto_20190220_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'TCK'), (2, 'TMK'), (3, 'Constitution')])),
                ('no', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
        migrations.CreateModel(
            name='IndictmentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='type')),
            ],
            options={
                'verbose_name': 'indictment class',
                'verbose_name_plural': 'indictment classes',
            },
        ),
        migrations.AddField(
            model_name='indictment',
            name='articles',
            field=models.ManyToManyField(to='cases.Article', verbose_name='articles'),
        ),
        migrations.AddField(
            model_name='indictmenttype',
            name='indictment_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.IndictmentClass', verbose_name='indictment class'),
        ),
    ]
