# Generated by Django 2.1.5 on 2019-03-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_auto_20190316_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified time'),
        ),
    ]
