# Generated by Django 2.1.5 on 2019-02-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_auto_20190220_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestatus',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='details'),
        ),
    ]
