# Generated by Django 2.1.5 on 2019-03-23 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0025_auto_20190323_1108'),
        ('cases', '0016_auto_20190322_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casedocument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trialdocument',
            name='description',
        ),
        migrations.AddField(
            model_name='casedocument',
            name='journalist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Journalist', verbose_name='journalist'),
        ),
        migrations.AddField(
            model_name='trialdocument',
            name='journalist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Journalist', verbose_name='journalist'),
        ),
        migrations.AddField(
            model_name='trialdocument',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='publish'),
        ),
    ]
