# Generated by Django 2.1.5 on 2019-02-21 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_casestatus_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseIndictment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True, verbose_name='details')),
                ('date', models.DateField(verbose_name='date')),
                ('articles', models.ManyToManyField(to='cases.Article', verbose_name='articles')),
            ],
            options={
                'verbose_name': 'indictment',
                'verbose_name_plural': 'indictments',
            },
        ),
        migrations.RemoveField(
            model_name='indictmenttype',
            name='indictment_class',
        ),
        migrations.AlterModelOptions(
            name='indictment',
            options={'verbose_name': 'indictment type', 'verbose_name_plural': 'indictment types'},
        ),
        migrations.RemoveField(
            model_name='indictment',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='indictment',
            name='case',
        ),
        migrations.RemoveField(
            model_name='indictment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='indictment',
            name='details',
        ),
        migrations.RemoveField(
            model_name='indictment',
            name='type',
        ),
        migrations.AddField(
            model_name='case',
            name='coup_related',
            field=models.BooleanField(default=False, verbose_name='coup related'),
        ),
        migrations.AddField(
            model_name='case',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='case',
            name='opening_date',
            field=models.DateField(blank=True, null=True, verbose_name='case opening date'),
        ),
        migrations.AddField(
            model_name='indictment',
            name='category',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='indictment',
            name='definition',
            field=models.CharField(default='-', max_length=200, verbose_name='type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='filing_date',
            field=models.DateField(blank=True, null=True, verbose_name='case filing date'),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'local'), (1, 'appeal'), (2, 'supreme'), (3, 'constitutional'), (4, 'ECHR')], default=1),
        ),
        migrations.DeleteModel(
            name='IndictmentClass',
        ),
        migrations.DeleteModel(
            name='IndictmentType',
        ),
        migrations.AddField(
            model_name='caseindictment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case', verbose_name='case'),
        ),
        migrations.AddField(
            model_name='caseindictment',
            name='indictmen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.Indictment', verbose_name='indictment type'),
        ),
    ]
