# Generated by Django 2.1.5 on 2019-03-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_auto_20190323_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casedocument',
            options={'ordering': ('case', 'type'), 'verbose_name': 'case document', 'verbose_name_plural': 'case documents'},
        ),
        migrations.AlterModelOptions(
            name='casedocumenttype',
            options={'ordering': ('order', 'id'), 'verbose_name': 'case document type', 'verbose_name_plural': 'case document types'},
        ),
        migrations.AlterModelOptions(
            name='casenote',
            options={'ordering': ('case', 'type'), 'verbose_name': 'case note', 'verbose_name_plural': 'case notes'},
        ),
        migrations.AlterModelOptions(
            name='casenotetype',
            options={'ordering': ('order', 'id'), 'verbose_name': 'case note type', 'verbose_name_plural': 'case note types'},
        ),
        migrations.AlterModelOptions(
            name='trialdocument',
            options={'ordering': ('trial', 'type'), 'verbose_name': 'trial document', 'verbose_name_plural': 'trial documents'},
        ),
        migrations.AlterModelOptions(
            name='trialnote',
            options={'ordering': ('trial', 'type'), 'verbose_name': 'trial note', 'verbose_name_plural': 'trial notes'},
        ),
        migrations.AlterModelOptions(
            name='trialnotetype',
            options={'ordering': ('order', 'id'), 'verbose_name': 'trial note type', 'verbose_name_plural': 'trial note types'},
        ),
        migrations.AlterModelOptions(
            name='trialviolation',
            options={'ordering': ('trial', 'type'), 'verbose_name': 'right violation', 'verbose_name_plural': 'right violations'},
        ),
        migrations.AlterModelOptions(
            name='violationtype',
            options={'ordering': ('order', 'id'), 'verbose_name': 'violation type', 'verbose_name_plural': 'violation types'},
        ),
        migrations.AddField(
            model_name='casedocumenttype',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='casenotetype',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='trialdocumenttype',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='trialnotetype',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='violationtype',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='order'),
        ),
    ]
