# Generated by Django 2.1.5 on 2019-02-23 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_auto_20190221_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jurisdiction.Court', verbose_name='court'),
        ),
        migrations.AlterField(
            model_name='case',
            name='no',
            field=models.CharField(max_length=20, verbose_name='file number'),
        ),
    ]
