# Generated by Django 2.1.5 on 2019-04-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_case_complainant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casejournalist',
            name='attorneys',
            field=models.ManyToManyField(blank=True, to='people.Attorney', verbose_name='attorney'),
        ),
    ]
