# Generated by Django 2.1.5 on 2019-04-18 12:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_auto_20190403_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='summary',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='case summary'),
        ),
        migrations.AlterField(
            model_name='casedecision',
            name='decision_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'acquittal'), (1, 'fine'), (2, 'imprisonment'), (6, 'postponed'), (7, 'judgement receded'), (8, 'discontinued')], null=True, verbose_name='decision type'),
        ),
        migrations.AlterField(
            model_name='casenote',
            name='note',
            field=tinymce.models.HTMLField(verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='details',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='summary',
            field=tinymce.models.HTMLField(verbose_name='case summary'),
        ),
        migrations.AlterField(
            model_name='trialdecision',
            name='decision_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'acquittal'), (1, 'fine'), (2, 'imprisonment'), (6, 'postponed'), (7, 'judgement receded'), (8, 'discontinued')], null=True, verbose_name='decision type'),
        ),
        migrations.AlterField(
            model_name='trialnote',
            name='note',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='note'),
        ),
    ]
