# Generated by Django 2.1.5 on 2019-04-23 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0028_auto_20190418_1218'),
        ('cases', '0024_casejournalist_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casejournalist',
            name='summary',
        ),
        migrations.AddField(
            model_name='casenote',
            name='journalist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Journalist', verbose_name='journalist'),
        ),
    ]
