# Generated by Django 2.1.5 on 2019-04-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_auto_20190423_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casenote',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.Case', verbose_name='case'),
        ),
    ]
