# Generated by Django 2.1.5 on 2019-04-23 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0027_auto_20190423_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casenote',
            options={'ordering': ('case__name', 'type'), 'verbose_name': 'trial brief', 'verbose_name_plural': 'trial briefs'},
        ),
    ]
