# Generated by Django 2.1.5 on 2019-04-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0030_auto_20190426_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='order'),
        ),
    ]
