# Generated by Django 2.1.5 on 2019-04-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0031_auto_20190427_0422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casenote',
            options={'ordering': ('case__name', 'type'), 'verbose_name': 'trial notes', 'verbose_name_plural': 'trial notes'},
        ),
    ]
