# Generated by Django 2.1.5 on 2019-05-08 14:38

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0032_auto_20190427_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casenote',
            options={'ordering': ('case__name', 'type'), 'verbose_name': 'case notes', 'verbose_name_plural': 'case notes'},
        ),
        migrations.AddField(
            model_name='case',
            name='summary_en',
            field=martor.models.MartorField(blank=True, null=True, verbose_name='case summary (EN)'),
        ),
        migrations.AddField(
            model_name='casenote',
            name='lang',
            field=models.CharField(choices=[('tr', 'Turkish'), ('en', 'English')], default='tr', max_length=5, verbose_name='language'),
        ),
    ]
