# Generated by Django 2.1.5 on 2019-05-08 18:05

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0034_remove_casenote_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='casenote',
            name='note_en',
            field=martor.models.MartorField(blank=True, null=True, verbose_name='note'),
        ),
    ]
