# Generated by Django 2.1.5 on 2019-05-08 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0036_auto_20190508_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ('name', 'order', '-modified'), 'verbose_name': 'case', 'verbose_name_plural': 'cases'},
        ),
    ]
