# Generated by Django 2.1.5 on 2019-05-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0038_case_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ('slug', 'order', '-modified'), 'verbose_name': 'case', 'verbose_name_plural': 'cases'},
        ),
        migrations.AddField(
            model_name='case',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='case name'),
        ),
    ]
