# Generated by Django 2.1.5 on 2019-06-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0039_auto_20190514_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='case name (EN)'),
        ),
    ]
