# Generated by Django 2.1.5 on 2019-07-08 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0040_auto_20190614_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='complainant',
        ),
    ]
