# Generated by Django 2.1.5 on 2019-07-25 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0042_trial_inst_observers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial',
            name='observers',
        ),
    ]
