# Generated by Django 2.1.5 on 2019-07-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0043_remove_trial_observers'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocumenttype',
            name='type_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='trialdocumenttype',
            name='type_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='type'),
        ),
    ]
