# Generated by Django 2.1.5 on 2019-08-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0044_auto_20190729_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedecision',
            name='punishment_life_sentence',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'life sentence'), (2, 'aggravated life sentence')], null=True, verbose_name='life sentence'),
        ),
    ]
