# Generated by Django 2.1.5 on 2019-08-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0045_casedecision_punishment_life_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestatus',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'local'), (1, 'appeal'), (2, 'supreme'), (3, 'constitutional'), (4, 'ECHR')]),
        ),
    ]
