# Generated by Django 2.1.5 on 2019-08-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0046_auto_20190819_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestatus',
            options={'verbose_name': 'case status', 'verbose_name_plural': 'case status'},
        ),
        migrations.RemoveField(
            model_name='casestatus',
            name='date',
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'local'), (1, 'appeal'), (2, 'supreme'), (5, 'abatement of action'), (6, 'decision of reversal')]),
        ),
    ]
