# Generated by Django 2.1.5 on 2019-08-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0047_auto_20190819_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestatus',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'local'), (1, 'appeal'), (2, 'supreme'), (5, 'abatement of action'), (6, 'decision of reversal'), (7, 'rejected')]),
        ),
    ]
