# Generated by Django 2.1.5 on 2019-10-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0049_auto_20190911_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'TCK'), (2, 'TMK'), (4, 'MİT'), (5, 'TGYK'), (6, 'Press Law')]),
        ),
    ]
