# Generated by Django 2.1.5 on 2020-01-16 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0050_auto_20191001_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casejournalist',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.Case', verbose_name='case'),
        ),
    ]
