# Generated by Django 2.1.5 on 2020-07-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0051_auto_20200116_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'TCK'), (2, 'TMK'), (4, 'MİT'), (5, 'TGYK'), (6, 'Press Law'), (7, 'SPK')]),
        ),
    ]
