# Generated by Django 2.1.5 on 2020-07-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0052_auto_20200702_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=250, verbose_name='case name'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='case name (EN)'),
        ),
    ]
