# Generated by Django 2.1.5 on 2020-09-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0053_auto_20200710_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'TCK'), (2, 'TMK'), (4, 'MİT'), (5, 'TGYK'), (6, 'Press Law'), (7, 'SPK'), (8, 'Banking Law')]),
        ),
    ]
