# Generated by Django 2.1.5 on 2019-02-06 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'penal court'), (2, 'criminal court'), (3, 'court of appeal'), (4, 'supreme court'), (5, 'constitutional court'), (6, 'ECHR')], null=True, verbose_name='type')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jurisdiction.City', verbose_name='city')),
            ],
            options={
                'verbose_name': 'court',
                'verbose_name_plural': 'courts',
            },
        ),
        migrations.CreateModel(
            name='Prison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('type', models.CharField(blank=True, choices=[('e', 'Type E'), ('f', 'Type F')], max_length=1, null=True, verbose_name='type')),
            ],
            options={
                'verbose_name': 'prison',
                'verbose_name_plural': 'prisons',
            },
        ),
    ]
