# Generated by Django 2.1.5 on 2019-02-04 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attorney',
            options={'verbose_name': 'attorney', 'verbose_name_plural': 'attorneys'},
        ),
        migrations.AlterModelOptions(
            name='court',
            options={'verbose_name': 'court', 'verbose_name_plural': 'courts'},
        ),
        migrations.AlterModelOptions(
            name='courttype',
            options={'verbose_name': 'court type', 'verbose_name_plural': 'court types'},
        ),
        migrations.AlterModelOptions(
            name='decisiontype',
            options={'verbose_name': 'decision type', 'verbose_name_plural': 'decision types'},
        ),
        migrations.AlterModelOptions(
            name='indictmenttype',
            options={'verbose_name': 'indictment type', 'verbose_name_plural': 'indictment types'},
        ),
        migrations.AlterModelOptions(
            name='judge',
            options={'verbose_name': 'judge', 'verbose_name_plural': 'judges'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'location', 'verbose_name_plural': 'locations'},
        ),
        migrations.AlterModelOptions(
            name='prison',
            options={'verbose_name': 'prison', 'verbose_name_plural': 'prisons'},
        ),
        migrations.AlterModelOptions(
            name='prisontype',
            options={'verbose_name': 'prison type', 'verbose_name_plural': 'prison types'},
        ),
        migrations.AlterModelOptions(
            name='prosecutor',
            options={'verbose_name': 'prosecutor', 'verbose_name_plural': 'prosecutors'},
        ),
        migrations.AlterModelOptions(
            name='punishmenttype',
            options={'verbose_name': 'punishment type', 'verbose_name_plural': 'punishment types'},
        ),
        migrations.AlterModelOptions(
            name='trialtype',
            options={'verbose_name': 'trial type', 'verbose_name_plural': 'trial types'},
        ),
        migrations.AlterModelOptions(
            name='violationtype',
            options={'verbose_name': 'violation type', 'verbose_name_plural': 'violation types'},
        ),
        migrations.AlterField(
            model_name='attorney',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='court',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jurisdiction.Location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='court',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='court',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jurisdiction.CourtType', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='courttype',
            name='type',
            field=models.CharField(max_length=50, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='decisiontype',
            name='type',
            field=models.CharField(max_length=100, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='indictmenttype',
            name='type',
            field=models.CharField(max_length=200, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='prison',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='prison',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jurisdiction.PrisonType', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='prisontype',
            name='type',
            field=models.CharField(max_length=50, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='prosecutor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='punishmenttype',
            name='type',
            field=models.CharField(max_length=50, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='trialtype',
            name='type',
            field=models.CharField(max_length=100, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='violationtype',
            name='type',
            field=models.CharField(max_length=100, verbose_name='type'),
        ),
    ]
