# Generated by Django 2.1.5 on 2019-02-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0002_auto_20190207_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='name',
        ),
        migrations.AddField(
            model_name='court',
            name='no',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='court',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'penal court'), (2, 'criminal court'), (3, 'court of appeal'), (4, 'supreme court'), (5, 'constitutional court'), (6, 'ECHR')], default=1, verbose_name='type'),
        ),
    ]
