# Generated by Django 2.1.5 on 2019-03-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0003_auto_20190207_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',), 'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ('city',), 'verbose_name': 'court', 'verbose_name_plural': 'courts'},
        ),
        migrations.AlterField(
            model_name='court',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Penal Court'), (2, 'Criminal Court'), (3, 'Court of Appeal'), (4, 'Supreme Court'), (5, 'Constitutional Court'), (6, 'ECHR')], default=1, verbose_name='type'),
        ),
    ]
