# Generated by Django 2.1.5 on 2019-04-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0005_auto_20190329_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Civil Court'), (1, 'Penal Court'), (2, 'Criminal Court'), (3, 'Court of Appeal'), (4, 'Supreme Court'), (5, 'Constitutional Court'), (6, 'ECHR')], default=1, verbose_name='type'),
        ),
    ]
