# Generated by Django 2.1.5 on 2019-10-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0007_prison_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Civil Court'), (1, 'Penal Court'), (2, 'Criminal Court'), (3, 'Court of Appeal'), (4, 'Supreme Court'), (5, 'Constitutional Court'), (6, 'ECHR'), (7, 'Commercial Court')], default=1, verbose_name='type'),
        ),
    ]
