# Generated by Django 2.1.5 on 2019-03-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_auto_20190310_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ('name',), 'verbose_name': 'institution', 'verbose_name_plural': 'institutions'},
        ),
    ]
