# Generated by Django 2.1.5 on 2019-07-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_auto_20190323_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'observer',
                'verbose_name_plural': 'observers',
                'ordering': ('name',),
            },
        ),
    ]
