# Generated by Django 2.1.5 on 2019-03-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'carousel', 'verbose_name_plural': 'carousel'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
        migrations.AlterField(
            model_name='carousel',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='photo',
            field=models.ImageField(upload_to='carousel/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='text',
            field=models.CharField(max_length=250, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
