# Generated by Django 2.1.5 on 2019-03-16 15:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190316_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 3, 16, 15, 33, 39, 553953, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 3, 16, 15, 33, 48, 893542, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
    ]
