# Generated by Django 2.1.5 on 2019-03-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190316_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ('-added',), 'verbose_name': 'carousel', 'verbose_name_plural': 'carousel'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-added',), 'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
    ]
