# Generated by Django 2.1.5 on 2019-03-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190318_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='photo',
            new_name='image',
        ),
    ]
