# Generated by Django 2.1.5 on 2019-03-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190318_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='summary',
            new_name='text',
        ),
    ]
