# Generated by Django 2.1.5 on 2019-04-25 20:52

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20190418_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=martor.models.MartorField(verbose_name='text'),
        ),
    ]
