# Generated by Django 2.1.5 on 2019-04-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
