# Generated by Django 2.1.5 on 2019-04-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20190427_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='model_name',
            field=models.CharField(default='trial', max_length=50),
            preserve_default=False,
        ),
    ]
