# Generated by Django 2.1.5 on 2019-04-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20190427_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='model_name',
        ),
    ]
