# Generated by Django 2.1.5 on 2019-06-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_remove_feed_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='text_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='text'),
        ),
    ]
