# Generated by Django 2.1.5 on 2019-07-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_carousel_text_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='text_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='text (EN)'),
        ),
    ]
