# Generated by Django 2.1.5 on 2019-09-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20190911_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='value',
            field=models.CharField(max_length=500, verbose_name='value'),
        ),
    ]
